### ISSUE TITLE
Make the toolbar optional.

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-fabric#67]
**Is your feature request related to a problem? Please describe.**
I wanted to work with my own toolbar and use the tubular fabric list.

**Describe the solution you'd like**
I would like to have an option to deactivate the toolbar on the grid.

**Additional context**

![image](https://user-images.githubusercontent.com/26309079/76114510-d96bfa00-5fab-11ea-852c-3ee68a892b52.png)

**Comment by geoperez** [comment]
Closing.
